#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# The 1Password Secure Note that contains the env var mapping.
# The note content should be lines of: VARIABLE_NAME=op://Vault/Item/field
#
# Create it once with:
#   op item create \
#     --category="Secure Note" \
#     --title="Shell Env Config" \
#     "--vault=System Credentials" \
#     notesPlain="GITHUB_USERNAME=op://System Credentials/GitHub/username
#   GITHUB_TOKEN=op://System Credentials/GitHub/token"
#
# Override the vault/item with env vars if your structure differs.
OP_ENV_VAULT="${OP_ENV_VAULT:-System Credentials}"
OP_ENV_ITEM="${OP_ENV_ITEM:-Shell Env Config}"
OP_ENV_REF="op://${OP_ENV_VAULT}/${OP_ENV_ITEM}/notesPlain"

# Local cache of the mapping — contains op:// references only, no secrets.
OP_ENV_DIR="$HOME/.config/op"
OP_ENV_FILE="$OP_ENV_DIR/env.op"

install_env() {
    step "Installing load-secrets shell function"

    if ! command_exists op; then
        warn "1Password CLI not installed — run the onepassword module first."
        warn "Rerun this module after: ./bootstrap.sh env"
        return
    fi

    mkdir -p "$OP_ENV_DIR"
    chmod 700 "$OP_ENV_DIR"

    write_load_secrets_function

    if ! op whoami &>/dev/null 2>&1; then
        warn "1Password CLI not signed in — skipping secret fetch."
        warn "Run 'load-secrets' in any shell session to load secrets once signed in."
    else
        fetch_env_config
    fi

    log "env setup complete."
    log "Run 'load-secrets' in any shell session to load variables from 1Password into memory."
    log "Run 'load-secrets --refresh' to re-fetch the config mapping and reload."
}

fetch_env_config() {
    log "Fetching env config mapping from 1Password ($OP_ENV_REF)..."

    local config
    config=$(op read "$OP_ENV_REF" 2>/dev/null) \
        || error "Could not read $OP_ENV_REF. Check the item exists in 1Password."

    if [[ -z "$config" ]]; then
        warn "Env config is empty at $OP_ENV_REF — no secrets to load."
        return
    fi

    printf '%s\n' "$config" > "$OP_ENV_FILE"
    chmod 600 "$OP_ENV_FILE"
    log "Env config cached at $OP_ENV_FILE"
}

write_load_secrets_function() {
    local function_file="$OP_ENV_DIR/load-secrets.zsh"

    # Pass the configured references into the generated file at write time
    cat > "$function_file" << EOF
# Auto-generated by bootstrap — do not edit manually.
# Regenerate with: ./bootstrap.sh env

_op_env_file="\$HOME/.config/op/env.op"
_op_env_ref="${OP_ENV_REF}"

load-secrets() {
    local refresh=false
    [[ "\${1:-}" == "--refresh" ]] && refresh=true

    if ! command -v op &>/dev/null; then
        print -P "%F{red}[ERROR]%f  1Password CLI not installed."
        return 1
    fi

    if ! op whoami &>/dev/null 2>&1; then
        print -P "%F{yellow}[WARN]%f  Not signed in to 1Password."
        read -q "reply?Sign in now via op signin? [y/N] "
        echo
        if [[ "\$reply" == "y" ]]; then
            # eval is required to capture and apply the session token exported by op signin.
            # Safe here: evaluates official 1Password CLI output only, not user input.
            eval "\$(op signin)" || { print -P "%F{red}[ERROR]%f  op signin failed."; return 1; }
        else
            print -P "%F{yellow}[WARN]%f  Continuing without signing in — secret reads will likely fail."
        fi
    fi

    # Re-fetch the mapping config from 1Password if requested or missing
    if [[ "\$refresh" == true ]] || [[ ! -f "\$_op_env_file" ]]; then
        print -P "%F{blue}[INFO]%f  Fetching env config from 1Password..."
        local config
        config=\$(op read "\$_op_env_ref" 2>/dev/null) || {
            print -P "%F{red}[ERROR]%f  Could not read \$_op_env_ref"
            return 1
        }
        printf '%s\n' "\$config" > "\$_op_env_file"
        chmod 600 "\$_op_env_file"
    fi

    local count=0 var ref value
    while IFS= read -r line; do
        [[ "\$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "\${line// }"            ]] && continue

        var="\${line%%=*}"
        ref="\${line#*=}"

        if value=\$(op read "\$ref" 2>/dev/null); then
            export "\${var}=\${value}"
            (( count++ ))
        else
            print -P "%F{yellow}[WARN]%f  Could not read \$ref — skipping \$var"
        fi
    done < "\$_op_env_file"

    export SECRETS_LOADED=1
    print -P "%F{green}[INFO]%f  \$count secret(s) loaded into shell session (memory only, not on disk)."
}
EOF

    chmod 600 "$function_file"
    log "load-secrets function written to $function_file"
}

[[ "${BASH_SOURCE[0]}" != "${0}" ]] || { check_not_root && install_env; }
